channels:
- conda-forge
dependencies:
- python=3.10.13
- pip<=22.3.1
- pip:
  - mlflow==2.9.2
  - lz4==4.3.2
  - numpy==1.26.4
  - pandas==2.1.4
  - pathlib==1.0.1
  - psutil==5.9.0
  - scikit-learn==1.3.0
  - scipy==1.11.4
  - typing-extensions==4.9.0
  - xgboost==2.0.3
name: mlflow-env
